require('./ui-alignment/ai-image.test.cjs')
require('./ui-alignment/playground.test.cjs')
require('./ui-alignment/community.test.cjs')
require('./ui-alignment/gamification.test.cjs')
require('./ui-alignment/home.test.cjs')
